apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}

  updateStrategy:
    type: {{ .Values.updateStrategy }}

  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: transmission
        image: {{ .Values.image.name}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: port
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          tcpSocket:
            port: port
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: port
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.env }}
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
{{- end }}
