# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.31.243.157:5000/day1118/jx-test
  tag: 0.0.5
  pullPolicy: IfNotPresent
service:
  name: jx-test
  type: ClusterIP
  externalPort: 80
  internalPort: 9091
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
 TR_RATIO_LIMIT: "0"
 TR_RATIO_LIMIT_ENABLED: "true"
 TR_RPC_AUTHENTICATION_REQUIRED: "false"
 TR_DOWNLOAD_DIR: "/downloads/complete"
 TR_INCOMPLETE_DIR: "/downloads/incomplete"
 TR_INCOMPLETE_DIR_ENABLED: "true"     
ingress:
  enabled: false
